{
 "title": "IIOT_DATA_PIPELINE",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Utilization",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    machine_id, \r\n    (sum(status) * 100.0) / count() as utilization \r\nFROM machine_data \r\nWHERE $__timeFilter(timestamp) \r\nGROUP BY machine_id\r\nORDER BY machine_id",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Running vs Stopped",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    CASE WHEN status = 1 THEN 'Running' ELSE 'Stopped' END as state,\r\n    count(*) as total\r\nFROM machine_data\r\nWHERE $__timeFilter(timestamp)\r\nGROUP BY status\r\n",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Production Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 17, "x": 7, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT machine_id, max(production_count) as Total\r\nFROM machine_data\r\nWHERE $__timeFilter(timestamp)\r\nGROUP BY machine_id\r\n",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Temp Trend",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, avg(temperature) as temp, machine_id\r\nFROM machine_data\r\nWHERE $__timeFilter(timestamp)\r\nSAMPLE BY 1m ALIGN TO CALENDAR\r\n",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Machine status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, machine_id, status \r\nFROM machine_data \r\nWHERE $__timeFilter(timestamp)\r\nORDER BY machine_id\r\n",
     "selectedFormat": 2
    }
   ]
  }
 ]
}