# Mosquitto config for local development

listener 1883
allow_anonymous true
persistence true
persistence_file /mosquitto/data/mosquitto.db
log_dest stdout

connection emqx_bridge
address a21222cf.ala.asia-southeast1.emqxsl.com:8883
remote_clientid mosquitto_bridge
remote_username gowtham1
remote_password Gowtham@2004
bridge_cafile /mosquitto/config/certs/emqxsl-ca.crt
bridge_tls_version tlsv1.2
bridge_protocol_version mqttv311
bridge_insecure false
try_private false
topic factory/# out 0
start_type automatic
notifications true
